### ISSUE TITLE
Reuse current clusters?

### ISSUE THREAD

**Issue by raulriera** [infinum/FBAnnotationClustering#2]
Hi,

I have implemented your pod and it works great so far, but after I added some animations with the `didAddAnnotationViews` method I noticed that the clusters are always added to the map. Is there a way to only add "new" clusters?

If you look at the normal pin implementation, they are animated only once and they remain on the map until they are removed

**Comment by Quentin-Malgaud** [comment]
Hi everyone, and thank you again @filipbec for this wonderful library.
I am facing the same issue as @raulriera. But I am working in Swift. Unfortunately I am not able to wrap my head around this issue. Could anyone give me some hints on where the above snippet is implemented and where it is called. 
I hope with those answers will allow to make this work, and post the swift translation here

Thank you very much.

**Comment by RodBrown1988** [comment]
You have two options in Swift. You can add an extension to FBAnnotationCluster, where you define the above fixes (specifically hash and isEqual:) translated to Swift, or you can do it as a category in Objective-C, and continue to use the classes from Swift. 

If you choose the Obj-C route in your otherwise swift code, you don't require to add the header for the category to a bridging header, nor do you need to add any detail into the header for the category, as all you're doing is adding method overrides to the class in the Objective-C runtime. Simply add a category, define the above methods, and ensure the .m file is in the build phase for the product you wish to build. That will add the method to FBAnnotatonCluster at runtime.
