### ISSUE TITLE
Error EXC_BAD_ACCESS when add too many annotations 30K annotation

### ISSUE THREAD

**Issue by ghost** [infinum/FBAnnotationClustering#32]
Please help. Do anyone face the same problem like me. I testing on iPhone5 simulator 8.1. 

When the annotation is less than 10K everything work as expected, but after 30K annotations it keep error, crashing EXC_BAD_ACCESS Code:2 .

Thank you.

**Comment by filipbec** [comment]
I'm not able to reproduce this issue. Do you have the same problem with the example project?

**Comment by veyhong** [comment]
I have no problem with example.

**Comment by filipbec** [comment]
It might be the problem with your annotation objects. Please check if all annotations have valid coordinates.

**Comment by cvhong** [comment]
The 30K annotations is come from webservice and the object is include ObjectMapping, and I observe that the CPU is reach 99% then Memories warning and then the app freeze. could it be the problem of memories warning and iOS deallocated the object ?

**Comment by veyhong** [comment]
I found the problem: 
The problem is within the library. To reproduce the bug:
in FBViewController.m 
line 12 : #define kNUMBER_OF_LOCATIONS 20000 // change to 20K points annotation 
line 121:a.coordinate = CLLocationCoordinate2DMake(15.415599822998047, 101.57099914550781); // can change to any constant latitude and longitude this coordinate is in Bangkok Thailand area.

**Comment by Dundo7** [comment]
Hi, FBAnnotationClustering is no longer maintained.
